[package]
name = "flipper"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[dependencies]
ink = { path = "/home/andrew/code/ink/crates/ink", default-features = false }

[dev-dependencies]
ink_e2e = { path = "/home/andrew/code/ink/crates/e2e" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
]
ink-as-dependency = []
e2e-tests = []
